### ISSUE TITLE
Bug in cli_show_sessions function

### ISSUE THREAD

**Issue by davidfdezc** [OpenNOP/opennop#10]
Hi Justin,

It's David Fernández from SoloWAN team. Making some tests with the following monitoring command:
    watch "opennop show sessions"
we discovered that sometimes the command got into an infinite loop, consuming a 100% of a core.

Investigating the code we found that the cause is inside the cli_show_sessions function inside the sessionmanager module. The problem is that inside the main loop:

while (currentsession != NULL) {
   if ((currentsession->client != NULL) && (currentsession->server != NULL)) {
       ...show session data...
       currentsession = currentsession->next;
   }
}

The sentence "currentsession = currentsession->next;" should be out of the "if", because if you get into the loop when the session has been created but the client and server data has not been assigned, you get into an infinite loop.

Making that change the error disappeared in our case. 

Thanks and best regards,
David

**Comment by yaplej** [comment]
Thanks for pointing that out.  I think my merge request should fix it.
